"""Seed generator: Naver Shopping API -> sellers + products SQL files.

Usage:
    /path/to/ml/.venv/bin/python mini-coupang/shared/data/generate_seed.py

Requires .env (same directory) with:
    NAVER_CLIENT_ID=...
    NAVER_CLIENT_SECRET=...

Output:
    001_sellers.sql  (15 accounts + 15 sellers, preceded by TRUNCATE)
    002_products.sql (1000 products, seller_id resolved by seed email)

Both files are listed in shared/data/.gitignore and should not be committed.
"""
from __future__ import annotations

import json
import os
import random
import re
import sys
import time
from collections import Counter
from pathlib import Path

import bcrypt
import requests
from dotenv import load_dotenv

HERE = Path(__file__).parent
load_dotenv(HERE / ".env")

CLIENT_ID = os.environ["NAVER_CLIENT_ID"]
CLIENT_SECRET = os.environ["NAVER_CLIENT_SECRET"]

# Local category_id -> Naver Shopping query keyword.
CATEGORIES = {
    1: "텀블러",
    2: "노트북",
    3: "운동화",
    4: "키보드",
    5: "백팩",
}
PRODUCTS_PER_CATEGORY = 200  # 5 x 200 = 1000
SELLERS_COUNT = 15

API_URL = "https://openapi.naver.com/v1/search/shop.json"
HEADERS = {
    "X-Naver-Client-Id": CLIENT_ID,
    "X-Naver-Client-Secret": CLIENT_SECRET,
}

# Plain seed password; the hash is generated per run so BCryptPasswordEncoder
# on the Spring side accepts it. k6 scripts log in with this password.
SEED_PASSWORD = "test1234!"


def bcrypt_hash(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt(rounds=10)).decode("utf-8")


def fetch_page(query: str, start: int) -> list[dict]:
    r = requests.get(
        API_URL,
        headers=HEADERS,
        params={"query": query, "display": 100, "start": start, "sort": "sim"},
        timeout=10,
    )
    r.raise_for_status()
    return r.json().get("items", [])


HTML_TAG_RE = re.compile(r"</?[bB]>")


def clean_title(text: str) -> str:
    # Naver returns titles with <b>...</b> highlights around matched terms.
    return HTML_TAG_RE.sub("", text).strip()


def escape_sql(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "''")


def truncate(text: str, max_len: int) -> str:
    return text[:max_len]


def collect_products() -> list[tuple[int, str, str, int, str]]:
    """Return [(category_id, name, description, base_price, mall_name), ...]."""
    out: list[tuple[int, str, str, int, str]] = []
    for cid, query in CATEGORIES.items():
        print(f"[category {cid}] query={query!r}", file=sys.stderr)
        got = 0
        for start in range(1, PRODUCTS_PER_CATEGORY + 1, 100):
            items = fetch_page(query, start)
            if not items:
                break
            for item in items:
                name = truncate(clean_title(item.get("title", "")), 200)
                if len(name) < 2:
                    continue
                brand = (item.get("brand") or item.get("maker") or "").strip()
                description = truncate(f"{brand} {name}".strip(), 500)
                try:
                    price = int(item.get("lprice") or 0)
                except (TypeError, ValueError):
                    price = 0
                mall = truncate((item.get("mallName") or "네이버쇼핑").strip() or "네이버쇼핑", 100)
                out.append((cid, name, description, price, mall))
                got += 1
            time.sleep(0.1)
        print(f"[category {cid}] +{got} (total {len(out)})", file=sys.stderr)
    return out


def pick_sellers(products: list[tuple], count: int) -> list[str]:
    counter = Counter(p[4] for p in products)
    top = [m for m, _ in counter.most_common(count)]
    i = 1
    while len(top) < count:
        candidate = f"기본몰{i}"
        if candidate not in top:
            top.append(candidate)
        i += 1
    return top


def write_sellers_sql(sellers: list[str], path: Path) -> None:
    lines = [
        "-- Auto-generated by generate_seed.py",
        "-- DEV ONLY. Truncates all commerce tables before inserting 15 sellers.",
        "SET FOREIGN_KEY_CHECKS=0;",
        "TRUNCATE products;",
        "TRUNCATE product_options;",
        "TRUNCATE product_images;",
        "TRUNCATE sellers;",
        "TRUNCATE accounts;",
        "SET FOREIGN_KEY_CHECKS=1;",
        "",
    ]
    for i, mall in enumerate(sellers, start=1):
        email = f"seller{i}@seed.local"
        brn = f"1{i:09d}"
        phone = f"010{i:08d}"
        biz = escape_sql(mall)
        pwd_hash = bcrypt_hash(SEED_PASSWORD)
        lines.append(
            "INSERT INTO accounts (email, password_hash, created_at, updated_at) "
            f"VALUES ('{email}', '{pwd_hash}', NOW(), NOW());"
        )
        lines.append(
            "INSERT INTO sellers (account_id, business_name, business_registration_number, "
            "representative_name, phone_number, created_at, updated_at) VALUES ("
            f"LAST_INSERT_ID(), '{biz}', '{brn}', '판매자{i}', '{phone}', NOW(), NOW());"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_products_json(
    products: list[tuple[int, str, str, int, str]],
    sellers: list[str],
    path: Path,
) -> None:
    mall_to_idx = {m: i + 1 for i, m in enumerate(sellers)}
    rng = random.Random(42)
    out = []
    for cid, name, description, price, mall in products:
        idx = mall_to_idx.get(mall) or rng.randint(1, len(sellers))
        out.append({
            "categoryId": cid,
            "name": name,
            "description": description,
            "basePrice": price,
            "sellerIdx": idx,
        })
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")


def write_products_sql(
    products: list[tuple[int, str, str, int, str]],
    sellers: list[str],
    path: Path,
) -> None:
    mall_to_idx = {m: i + 1 for i, m in enumerate(sellers)}
    rng = random.Random(42)
    lines = [
        "-- Auto-generated by generate_seed.py",
        "-- Depends on 001_sellers.sql having been loaded.",
        "",
    ]
    for cid, name, description, price, mall in products:
        idx = mall_to_idx.get(mall) or rng.randint(1, len(sellers))
        email = f"seller{idx}@seed.local"
        lines.append(
            "INSERT INTO products (seller_id, category_id, name, description, base_price, "
            "status, created_at, updated_at) VALUES ("
            f"(SELECT s.seller_id FROM sellers s JOIN accounts a "
            f"ON s.account_id=a.account_id WHERE a.email='{email}'), "
            f"{cid}, '{escape_sql(name)}', '{escape_sql(description)}', {price}, "
            "'DRAFT', NOW(), NOW());"
        )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    products = collect_products()
    if not products:
        print("no products collected - check API key / quota", file=sys.stderr)
        return 1
    sellers = pick_sellers(products, SELLERS_COUNT)
    print(f"picked {len(sellers)} sellers: {sellers}", file=sys.stderr)
    write_sellers_sql(sellers, HERE / "001_sellers.sql")
    write_products_sql(products, sellers, HERE / "002_products.sql")
    write_products_json(products, sellers, HERE / "products.json")
    print(
        f"wrote 001_sellers.sql ({len(sellers)} rows), "
        f"002_products.sql ({len(products)} rows), "
        f"products.json ({len(products)} items)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
