CREATE DATABASE IF NOT EXISTS member  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS product CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS orders  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS payment CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS notification CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON member.*       TO 'mini'@'%';
GRANT ALL PRIVILEGES ON product.*      TO 'mini'@'%';
GRANT ALL PRIVILEGES ON orders.*       TO 'mini'@'%';
GRANT ALL PRIVILEGES ON payment.*      TO 'mini'@'%';
GRANT ALL PRIVILEGES ON notification.* TO 'mini'@'%';
FLUSH PRIVILEGES;
