global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    service: mini-coupang-backend

scrape_configs:
  - job_name: 'backend'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: mini-coupang-backend
