// scripts/generate-keyword-map.ts
import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import matter from 'gray-matter'

const POSTS_DIR = 'content/posts'
const OUTPUT_FILE = 'lib/generated/keyword-map.ts'

export interface BilingualText {
  ko: string
  en: string
}

export interface ScannedPost {
  file: string
  slug: string
  title: BilingualText
  summary: BilingualText
  keywords: string[]
}

export interface KeywordEntry {
  slug: string
  title: BilingualText
  summary: BilingualText
}

export interface Conflict {
  keyword: string
  files: Array<{ file: string; slug: string }>
}

function parseBilingual(raw: unknown, fieldName: string): BilingualText {
  if (
    raw &&
    typeof raw === 'object' &&
    !Array.isArray(raw) &&
    typeof (raw as Record<string, unknown>).ko === 'string' &&
    typeof (raw as Record<string, unknown>).en === 'string'
  ) {
    return {
      ko: (raw as Record<string, string>).ko,
      en: (raw as Record<string, string>).en,
    }
  }
  throw new Error(`frontmatter.${fieldName} must be { ko: string; en: string }`)
}

async function scanPosts(dir: string): Promise<ScannedPost[]> {
  const entries = await readdir(dir, { withFileTypes: true })
  const out: ScannedPost[] = []
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      out.push(...(await scanPosts(full)))
      continue
    }
    if (!entry.isFile() || !entry.name.endsWith('.mdx')) continue
    try {
      const raw = await readFile(full, 'utf8')
      const { data } = matter(raw)
      if (data.draft === true) continue
      if (typeof data.slug !== 'string') continue
      if (!Array.isArray(data.keywords)) continue
      out.push({
        file: relative(process.cwd(), full),
        slug: data.slug,
        title: parseBilingual(data.title, 'title'),
        summary: parseBilingual(data.summary, 'summary'),
        keywords: data.keywords.filter((k): k is string => typeof k === 'string'),
      })
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      throw new Error(`[keyword-map] failed to parse ${full}: ${msg}`)
    }
  }
  return out
}

export function buildMap(posts: readonly ScannedPost[]): {
  map: Map<string, KeywordEntry>
  conflicts: Conflict[]
} {
  const declarations = new Map<
    string,
    Array<{ file: string; slug: string; title: BilingualText; summary: BilingualText }>
  >()

  for (const post of posts) {
    for (const keyword of post.keywords) {
      if (keyword.length === 0) continue
      const key = keyword.toLowerCase()
      const list = declarations.get(key) ?? []
      list.push({ file: post.file, slug: post.slug, title: post.title, summary: post.summary })
      declarations.set(key, list)
    }
  }

  const map = new Map<string, KeywordEntry>()
  const conflicts: Conflict[] = []

  for (const [key, list] of declarations) {
    if (list.length > 1) {
      conflicts.push({
        keyword: key,
        files: list.map((d) => ({ file: d.file, slug: d.slug })),
      })
    } else {
      const [only] = list
      map.set(key, { slug: only.slug, title: only.title, summary: only.summary })
    }
  }

  return { map, conflicts }
}

export function formatConflictError(conflicts: readonly Conflict[]): string {
  const lines: string[] = ['[keyword-map] KEYWORD CONFLICT DETECTED', '']
  for (const c of conflicts) {
    lines.push(`Keyword "${c.keyword}" is declared in ${c.files.length} files:`)
    for (const f of c.files) {
      lines.push(`  - ${f.file} (slug: ${f.slug})`)
    }
    lines.push('')
  }
  lines.push("Resolution: Each keyword may only be declared in one post's frontmatter.")
  lines.push('Aborting build.')
  return lines.join('\n')
}

function escapeStringLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

function emitBilingual(b: BilingualText): string {
  return `{ ko: "${escapeStringLiteral(b.ko)}", en: "${escapeStringLiteral(b.en)}" }`
}

export function serializeMap(map: Map<string, KeywordEntry>): string {
  const entries = Array.from(map.entries())
  entries.sort(([a], [b]) => a.localeCompare(b))
  const byLength = entries
    .map(([kw]) => kw)
    .sort((a, b) => b.length - a.length || a.localeCompare(b))

  const header = [
    '// lib/generated/keyword-map.ts',
    '// DO NOT EDIT: generated by scripts/generate-keyword-map.ts',
    '',
    'export interface BilingualText {',
    '  ko: string',
    '  en: string',
    '}',
    '',
    'export interface KeywordEntry {',
    '  slug: string',
    '  title: BilingualText',
    '  summary: BilingualText',
    '}',
    '',
  ].join('\n')

  const mapEntries = entries
    .map(
      ([kw, e]) =>
        `  ["${escapeStringLiteral(kw)}", { slug: "${escapeStringLiteral(e.slug)}", title: ${emitBilingual(e.title)}, summary: ${emitBilingual(e.summary)} }],`,
    )
    .join('\n')

  const keywordMap = `export const KEYWORD_MAP: ReadonlyMap<string, KeywordEntry> = new Map([\n${mapEntries}\n])\n`

  const byLengthArr = byLength.map((kw) => `  "${escapeStringLiteral(kw)}",`).join('\n')
  const keywordsByLength = `export const KEYWORDS_BY_LENGTH: readonly string[] = [\n${byLengthArr}\n]\n`

  const slugEntries = Array.from(
    new Map(entries.map(([, e]) => [e.slug, e])).entries(),
  )
    .map(
      ([slug, e]) =>
        `  ["${escapeStringLiteral(slug)}", { slug: "${escapeStringLiteral(e.slug)}", title: ${emitBilingual(e.title)}, summary: ${emitBilingual(e.summary)} }],`,
    )
    .join('\n')

  const slugToEntry = `export const SLUG_TO_ENTRY: ReadonlyMap<string, KeywordEntry> = new Map([\n${slugEntries}\n])\n`

  return [header, keywordMap, '', keywordsByLength, '', slugToEntry].join('\n')
}

async function main() {
  const posts = await scanPosts(POSTS_DIR)
  const { map, conflicts } = buildMap(posts)

  if (conflicts.length > 0) {
    console.error(formatConflictError(conflicts))
    process.exit(1)
  }

  await mkdir('lib/generated', { recursive: true })
  await writeFile(OUTPUT_FILE, serializeMap(map), 'utf8')
  console.log(`[keyword-map] generated ${map.size} keywords from ${posts.length} posts`)
}

const isEntry =
  typeof process !== 'undefined' &&
  process.argv[1] !== undefined &&
  import.meta.url === `file://${process.argv[1]}`

if (isEntry) {
  main().catch((err) => {
    console.error('[keyword-map] fatal:', err)
    process.exit(1)
  })
}
